name: netwerk/text-bild
typeName: netwerk_textbild
group: default
prefixFields: true
prefixType: full
basics:
  - TYPO3/Appearance
  - TYPO3/Links
  - TYPO3/Categories
fields:
  -
    identifier: header
    type: Textarea
    useExistingField: false
  - identifier: bodytext
    type: Textarea
    enableRichtext: true
    richtextConfiguration: default
  - identifier: button
    type: Palette
    label: Button
    fields:
    - identifier: url
      type: Link
    - identifier: linktext
      type: Text
  -
    identifier: image
    type: File 
    label: 'Bild'
    useExistingField: false
    maxItems: 1
    allowed: common-image-types
    cropVariants:
      desktop:
        title: Desktop
        allowedAspectRatios:
          desktop:
            title: Hochformat
            value: 0.8
      mobile:
        title: mobile Version
        allowedAspectRatios:
          mobile:
            title: Querformat
            value: 2 / 1