name: netwerk/teaser-text
typeName: netwerk_teasertext
group: default
prefixFields: true
prefixType: full
basics:
  - TYPO3/Appearance
  - TYPO3/Links
  - TYPO3/Categories
fields:
  - identifier: subheader
    type: Text
  - identifier: header
    type: Text
  - identifier: header_layout
    useExistingField: true
  - identifier: items
    type: Collection
    label: Teaser-Items
    labelField: title
    fields:
      - identifier: image
        type: File
        useExistingField: false
        maxitems: 1
        allowed: common-image-types
        cropVariants:
          desktop:
            title: Desktop
            allowedAspectRatios:
              desktop:
                title: Hochformat
                value: 0.67
          mobile:
            title: mobile Version
            allowedAspectRatios:
              mobile:
                title: Hochformat
                value: 0.67
      - identifier: title
        type: Text
      - identifier: text
        type: Textarea
      - identifier: url
        type: Link
      - identifier: linktext
        type: Text
