name: netwerk/roomteaser
typeName: netwerk_roomteaser
group: default
prefixFields: true
prefixType: full
basics:
  - TYPO3/Appearance
  - TYPO3/Links
  - TYPO3/Categories
fields:
  - identifier: items
    type: Collection
    label: Teaser-Items
    labelField: title
    fields:
      - identifier: image
        type: File
        useExistingField: false
        allowed: common-image-types
        cropVariants:
          desktop:
            title: Desktop
            allowedAspectRatios:
              desktop:
                title: 3:2
                value: 3 / 2
      - identifier: title
        type: Text
      - identifier: subtitle
        type: Text
      - identifier: text
        type: Textarea
      - identifier: url
        type: Link
      - identifier: linktext
        type: Text
