<?php
return [
    'BE' => [
        'debug' => true,
        'installToolPassword' => '$argon2i$v=19$m=65536,t=16,p=1$dVA4YTZ1U0xFM2I0UU9SNg$pgdxkNeM5oyXXSrFcYpe5pNxuDx/xO+LPSXhODI/GiY',
        'passwordHashing' => [
            'className' => 'TYPO3\\CMS\\Core\\Crypto\\PasswordHashing\\Argon2iPasswordHash',
            'options' => [],
        ],
    ],
    'DB' => [
        'Connections' => [
            'Default' => [
                'charset' => 'utf8',
                'dbname' => false,
                'driver' => 'mysqli',
                'host' => false,
                'password' => false,
                'port' => '3306',
                'user' => false,
            ],
        ],
    ],
    'EXTCONF' => [
        'lang' => [
            'availableLanguages' => [
                'de',
            ],
        ],
    ],
    'EXTENSIONS' => [
        'backend' => [
            'backendFavicon' => '',
            'backendLogo' => '',
            'loginBackgroundImage' => '',
            'loginFootnote' => '',
            'loginHighlightColor' => '',
            'loginLogo' => '',
            'loginLogoAlt' => '',
        ],
        'cs_seo' => [
            'cropDescription' => '0',
            'evaluationDoktypes' => '1',
            'evaluators' => 'Title,Description,H1,H2,HeadingOrder,Images,Keyword',
            'excludeFileExtensions' => 'webp',
            'forceMinDescription' => '1',
            'inPageModule' => '0',
            'maxDescription' => '156',
            'maxH2' => '6',
            'maxNavTitle' => '50',
            'maxTitle' => '57',
            'minDescription' => '140',
            'minTitle' => '40',
            'modFileColumns' => 'title,description',
            'showDescriptionsInTCA' => '1',
        ],
        'extensionmanager' => [
            'automaticInstallation' => '1',
            'offlineMode' => '0',
        ],
        'ns_t3ai' => [
            'aIExceptionHandling' => '0',
            'aILogSolution' => '0',
            'aIPageCreation' => '1',
            'aiTcaRecord' => '1',
            'allowAiFileMeta' => '',
            'allowDefualtMetaGenerate' => '',
            'alttextApiKey' => '',
            'autoPageTranslate' => '0',
            'azure_api_endpoint' => '',
            'azure_api_key' => '',
            'azure_api_model' => 'Default',
            'azure_api_version' => '2024-02-01',
            'base' => 'https://emma.netwerk.guru/',
            'blockAICrawling' => '1',
            'checkCurrentStep' => '11',
            'checkStep' => 'finalStep',
            'claude_api_key' => '',
            'claude_api_model' => 'claude-3-opus-20240229',
            'content' => '',
            'contentFeature' => '1',
            'currentStep' => '11',
            'deepl_api_key' => '',
            'deepl_api_url' => 'https://api-free.deepl.com/v2',
            'deepseek_api_key' => '',
            'deepseek_frequency_penalty' => '0',
            'deepseek_logprobs' => '0',
            'deepseek_max_tokens' => '2048',
            'deepseek_model' => 'deepseek-chat',
            'deepseek_presence_penalty' => '0',
            'deepseek_response_format' => 'text',
            'deepseek_stop' => 'null',
            'deepseek_stream' => '0',
            'deepseek_stream_options' => 'null',
            'deepseek_temperature' => '0.7',
            'deepseek_tool_choice' => 'none',
            'deepseek_tools' => 'null',
            'deepseek_top_logprobs' => '0',
            'deepseek_top_p' => '0.01',
            'defaultAzureModel' => 'Default',
            'defaultClaudeModel' => 'claude-3-opus-20240229',
            'defaultContentType' => 'CurrentPage',
            'defaultDeepseekModel' => 'deepseek-chat',
            'defaultGeminiModel' => 'gemini-1.0-pro',
            'defaultModel' => 'openai',
            'defaultModelForTranslation' => 'openai',
            'defaultOllamaModel' => '',
            'defaultOpenAIModel' => 'gpt-4o',
            'defaultOpenaiModel' => 'gpt-4o',
            'defaultSERPView' => 'Desktop',
            'defaultTargetLanguageForTranslateWithT3ai' => 'de',
            'defaultXaiModel' => 'grok-2-latest',
            'defualtMetaModel' => '',
            'elevenlabsApiKey' => '',
            'em-ns_t3ai-websiteTypeOther' => '',
            'enableAllInOneSeo' => '1',
            'enableContentAnalysis' => '1',
            'enableContentRewriter' => '1',
            'enableDallEAIImages' => '1',
            'enableExtensionsLocalization' => '1',
            'enableLanguageTranslation' => '1',
            'enableMidJourney' => '1',
            'enableNewLocalization' => '1',
            'enableNewSEO' => '1',
            'enableNewsAdvance' => '1',
            'enableNewsSimple' => '1',
            'enableOpenverse' => '1',
            'enablePageAdvance' => '1',
            'enablePageSimple' => '1',
            'enablePageTree' => '1',
            'enablePexels' => '1',
            'enablePixabay' => '1',
            'enableSchema' => '1',
            'enableSeoMetaData' => '1',
            'enableSeoPageScore' => '1',
            'enableSerpSnippet' => '1',
            'enableSidebar' => '1',
            'enableSocialMediaMeta' => '1',
            'enableStabilityMedia' => '1',
            'enableUnsplash' => '1',
            'enable_ollama_model' => '1',
            'gemini_api_key' => '',
            'gemini_model' => 'gemini-1.0-pro',
            'google_api_key' => '',
            'google_api_url' => 'https://translation.googleapis.com/language/translate/v2',
            'google_page_speed_api' => '',
            'imageFormat' => '',
            'imageGenerateMode' => '',
            'imageSize' => '1024x1024',
            'imageStyle' => 'Realistic',
            'itemPerPage' => '',
            'media' => '',
            'mediaFeature' => '1',
            'mediaStorageFolder' => '',
            'midjourneyApiKey' => '',
            'newsDetailsPage' => '',
            'numberOfImage' => '1',
            'ollama_api_key' => '',
            'ollama_api_model' => '',
            'ollama_api_url' => '',
            'ollama_num_predict' => '',
            'ollama_temperature' => '',
            'ollama_top_k' => '',
            'ollama_top_p' => '',
            'openAiPromptPrefixDescriptionNumberOfResult' => '5',
            'openAiPromptPrefixKeywordsNumberOfResult' => '5',
            'openAiPromptPrefixOgDescriptionNumberOfResult' => '5',
            'openAiPromptPrefixOgTitleNumberOfResult' => '5',
            'openAiPromptPrefixPageTitleNumberOfResult' => '5',
            'openAiPromptPrefixTopicNumberOfResult' => '5',
            'openai_api_key' => getenv('OPENAI_API_KEY') ?: '',
            'openai_best_of' => '1',
            'openai_frequency_penalty' => '0.01',
            'openai_max_tokens' => '1300',
            'openai_model' => 'gpt-3.5-turbo',
            'openai_presence_penalty' => '0.01',
            'openai_temperature' => '0.7',
            'openai_top_p' => '0.01',
            'openverse_clientId' => '',
            'opeverseImageStyle' => '',
            'opeverse_clientsecret' => '',
            'optimizeSeo' => '1',
            'page' => '',
            'pageFeature' => '1',
            'pageId' => '1',
            'pexelsAccessKey' => '',
            'pixabayAccessKey' => '',
            'promptFeature' => '',
            'rteHistoryCount' => '3',
            'schemaNewsDetailId' => '',
            'seo' => '',
            'seoFeature' => '1',
            'setupWizard' => 1,
            'stabilityAiApiKey' => '',
            't3ai_company_description' => 'Ferienhaus in Stumm im Zillertal für bis zu 10 Personen',
            't3ai_website_category' => 'Travel and Hospitality',
            'techiesFeature' => '',
            'tone' => 'Formal',
            'translation' => '',
            'translationFeature' => '1',
            'typeOfContent' => 'Blog Posts',
            'unsplashAccessKey' => '',
            'useUrlForRequest' => '1',
            'websiteTitle' => 'Villa Emma',
            'xai_api_key' => '',
            'xai_max_tokens' => '16384',
            'xai_model' => 'grok-2-latest',
            'xai_response_format' => 'text',
            'xai_temperature' => '0.7',
        ],
        'staticfilecache' => [
            'backendDisplayMode' => 'both',
            'boostMode' => '0',
            'cacheTagsEnable' => '0',
            'clearCacheForAllDomains' => '1',
            'cspGenerationOverride' => '0',
            'debugHeaders' => '0',
            'disableInDevelopment' => '0',
            'enableGeneratorBrotli' => '0',
            'enableGeneratorGzip' => '1',
            'enableGeneratorPhp' => '0',
            'enableGeneratorPlain' => '0',
            'hashUriInCache' => '0',
            'htaccessTemplateName' => 'EXT:staticfilecache/Resources/Private/Templates/Htaccess.html',
            'inlineAssetsFileSize' => '50000',
            'inlineScriptMinify' => '0',
            'inlineServiceFavIcon' => '0',
            'inlineServiceScripts' => '0',
            'inlineServiceStyles' => '0',
            'inlineStyleAssets' => 'ico,png,woff2',
            'inlineStyleMinify' => '0',
            'largeIdentifierInCacheTable' => '0',
            'overrideCacheDirectory' => '',
            'overrideClientUserAgent' => '',
            'phpTemplateName' => 'EXT:staticfilecache/Resources/Private/Templates/Php.html',
            'rawurldecodeCacheFileName' => '0',
            'renameTablesToOtherPrefix' => '0',
            'sendCacheControlHeaderRedirectAfterCacheTimeout' => '0',
            'sendHttp2PushEnable' => '0',
            'sendHttp2PushFileExtensions' => 'css,js',
            'sendHttp2PushFileLimit' => '10',
            'sendHttp2PushLimitToArea' => '',
            'useFallbackMiddleware' => '1',
            'useReverseUriLengthInPriority' => '1',
            'validFallbackHeaders' => 'Content-Type,Content-Language,Content-Security-Policy,Link,X-SFC-Tags',
            'validHtaccessHeaders' => 'Content-Type,Content-Language,Content-Security-Policy,Link,X-SFC-Tags',
        ],
    ],
    'FE' => [
        'cacheHash' => [
            'enforceValidation' => true,
        ],
        'debug' => true,
        'disableNoCacheParameter' => true,
        'passwordHashing' => [
            'className' => 'TYPO3\\CMS\\Core\\Crypto\\PasswordHashing\\Argon2iPasswordHash',
            'options' => [],
        ],
    ],
    'GFX' => [
        'avif_quality' => 70,
        'imagefile_ext' => 'gif,jpg,jpeg,png,webp,avif,svg',
        'jpg_quality' => 70,
        'processor' => 'ImageMagick',
        'processor_allowUpscaling' => false,
        'processor_effects' => false,
        'processor_enabled' => true,
        'processor_path' => '',
        'processor_stripColorProfileCommand' => '+profile \\\'!iptc,*\\\'',
        'thumbnails' => true,
        'webp_quality' => 70,
    ],
    'LOG' => [
        'TYPO3' => [
            'CMS' => [
                'deprecations' => [
                    'writerConfiguration' => [
                        'notice' => [
                            'TYPO3\CMS\Core\Log\Writer\FileWriter' => [
                                'disabled' => false,
                            ],
                        ],
                    ],
                ],
            ],
        ],
    ],
    'MAIL' => [
        'transport' => 'sendmail',
        'transport_sendmail_command' => '/usr/local/bin/mailpit sendmail -t --smtp-addr 127.0.0.1:1025',
        'transport_smtp_encrypt' => '',
        'transport_smtp_password' => '',
        'transport_smtp_server' => '',
        'transport_smtp_username' => '',
    ],
    'SYS' => [
        'UTF8filesystem' => true,
        'caching' => [
            'cacheConfigurations' => [
                'hash' => [
                    'backend' => 'TYPO3\\CMS\\Core\\Cache\\Backend\\Typo3DatabaseBackend',
                ],
                'pages' => [
                    'backend' => 'TYPO3\\CMS\\Core\\Cache\\Backend\\Typo3DatabaseBackend',
                    'options' => [
                        'compression' => true,
                    ],
                ],
                'rootline' => [
                    'backend' => 'TYPO3\\CMS\\Core\\Cache\\Backend\\Typo3DatabaseBackend',
                    'options' => [
                        'compression' => true,
                    ],
                ],
            ],
        ],
        'devIPmask' => '*',
        'displayErrors' => 1,
        'encryptionKey' => 'e48bf018e5f1484b9ad83ea16f1fbb1ee80d63a9a4b1a028c14cf8e675e7c1852f3a6c880e349907a72549e5b2a0a526',
        'exceptionalErrors' => 12290,
        'features' => [
            'frontend.cache.autoTagging' => true,
        ],
        'sitename' => 'New TYPO3 site',
        'systemMaintainers' => [
            1,
            2,
        ],
    ],
];
