base: 'https://emma.netwerk.guru/'
baseVariants:
  -
    base: 'https://p688748.webspaceconfig.de/'
    condition: 'getenv("HTTP_HOST") == "p688748.webspaceconfig.de"'
  -
    base: 'https://emma.tirol.ddev.site/'
    condition: 'applicationContext == "Development"'
disableStaticFileCache: false
languages:
  -
    title: Deutsch
    enabled: true
    languageId: 0
    base: /
    locale: de_AT
    navigationTitle: Deutsch
    flag: at
    hreflang: de-AT
    websiteTitle: ''
rootPageId: 1
txCsseoXdefault: 0
websiteTitle: ''
