base: 'https://emma.netwerk.guru/'
baseVariants:
  -
    base: 'https://p688748.webspaceconfig.de/'
    condition: 'getenv("HTTP_HOST") == "p688748.webspaceconfig.de"'
  -
    base: 'https://emma.tirol.ddev.site/'
    condition: 'applicationContext == "Development"'
dependencies:
  - netwerk/nw-template
disableStaticFileCache: false
languages:
  -
    title: Deutsch
    enabled: true
    languageId: 0
    base: /
    locale: de_AT
    navigationTitle: Deutsch
    flag: at
    hreflang: de-AT
    websiteTitle: ''
  -
    title: Englisch
    enabled: true
    locale: en_US
    t3ai_speech: ''
    hreflang: en-US
    base: /en/
    websiteTitle: ''
    navigationTitle: Englisch
    fallbackType: strict
    fallbacks: ''
    flag: en-us-gb
    languageId: 1
rootPageId: 1
t3ai_company_description: ''
t3ai_website_category: Retail
txCsseoXdefault: 0
websiteTitle: ''
