name: netwerk/slogan
typeName: netwerk_slogan
group: default
prefixFields: true
prefixType: full
basics:
  - TYPO3/Appearance
  - TYPO3/Links
  - TYPO3/Categories
fields:
  -
    identifier: subheader
    type: Text
    label: Subheader
  - identifier: bodytext
    type: Textarea
    useExistingField: true
    enableRichtext: false
