name: netwerk/parallax
typeName: netwerk_parallax
group: default
prefixFields: true
prefixType: full
basics:
  - TYPO3/Appearance
  - TYPO3/Links
  - TYPO3/Categories
fields:
  -
    identifier: subheader
    useExistingField: true
  - 
    identifier: text
    type: Textarea
    enableRichtext: false
  -
    identifier: image
    type: File 
    label: 'Parallax-Bild'
    useExistingField: false
    maxItems: 1
    allowed: common-image-types
    cropVariants:
      desktop:
        title: Desktop
        allowedAspectRatios:
          desktop:
            title: 3:2
            value: 3 / 2
      mobile:
        title: mobile Version
        allowedAspectRatios:
          mobile:
            title: 4:5
            value: 4 / 5
