name: netwerk/facts
typeName: netwerk_facts
group: default
prefixFields: true
prefixType: full
basics:
  - TYPO3/Appearance
  - TYPO3/Links
  - TYPO3/Categories
fields:
  - identifier: facts
    type: Collection
    label: Fakten
    labelField: title
    maxitems: 3
    fields:
      - identifier: title
        type: Text
      - identifier: text
        type: Textarea
