name: netwerk/text-image-background
typeName: netwerk_textimagebackground
group: default
prefixFields: true
basics:
  - TYPO3/Appearance
  - TYPO3/Links
  - TYPO3/Categories
fields:
  -
    identifier: header
    useExistingField: true
  - identifier: button
    type: Palette
    label: Button
    fields:
    - identifier: url
      type: Link
    - identifier: linktext
      type: Text
  -
    identifier: image
    type: File 
    label: 'Hintergrundbild'
    useExistingField: false
    maxItems: 1
    allowed: common-image-types
    cropVariants:
      widescreen:
        title: Widescreen
        allowedAspectRatios:
          widescreen:
            title: 3:1
            value: 3 / 1
      standard-mobile:
        title: Standard Mobile
        allowedAspectRatios:
          standard-mobile:
            title: 2:1
            value: 2 / 1
      tall-mobile:
        title: Tall Mobile
        allowedAspectRatios:
          tall-mobile:
            title: 3:2
            value: 3 / 2