name: netwerk/image-round-text
typeName: netwerk_imageroundtext
group: default
prefixFields: true
prefixType: full
basics:
  - TYPO3/Appearance
  - TYPO3/Links
  - TYPO3/Categories
fields:
  -
    identifier: header
    useExistingField: true
  - identifier: bodytext
    type: Textarea
    enableRichtext: true
    richtextConfiguration: default
  -
    identifier: image
    type: File 
    label: 'Hintergrundbild'
    useExistingField: false
    maxItems: 1
    allowed: common-image-types
    cropVariants:
      universal:
        title: Universelles Format
        allowedAspectRatios:
          universal:
            title: 1:1
            value: 1 / 1
